server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  location = /pf-admin {
    return 308 /pf-admin/;
  }

  location /pf-admin/ {
    try_files $uri $uri/ /pf-admin/index.html;
  }
}
