services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    networks:
      - printforge

volumes:
  fastify_node_modules:
  fastify_workspace_node_modules:
  admin_node_modules:
  admin_workspace_node_modules:
  configurator_node_modules:
  configurator_workspace_node_modules:

networks:
  printforge:
    external: true
